### PR TITLE
Update for backbone 0.9.0 support.

### PR DESCRIPTION
**Pull request by latentflip**
The only thing that seems to be needed is to rename all references to `collection._add` and `collection._remove` to `collection.add` and `collection.remove` since Backbone was refactored to remove `_add` and `_remove`.

The tests all pass, however I am a little concerned that all the tests pass even when I use Backbone v0.5.3. Does anyone know the rationale behind using `_add` instead of `add` in the first place?

As far as I can tell, using `_add` in Backbone 0.5.3 bypassed sorting of the collection, and triggering of `add` events on the models being added. Not sure if that's going to cause issues.

### CODE REVIEW

**Comment by saimonmoore** [comment]
Again...another nice commit. Here at teambox we still haven't made the switch to backbone 0.9.0. When we get the time we'll do so and pull this. Thanks

**Comment by francois2metz** [comment]
Any update on this pull request?

**Comment by masylum** [comment]
I will create a branch for 0.9.x.
We don´t use Backbone 0.9.x at Teambox so it will not be as battle-hardened as the 0.5.x branch.

**Comment by masylum** [comment]
There is a maintained branch supporting latest backbone called `latest_backbone`. All tests passing and benchmarks show no peformance regression :)

**Comment by masylum** [comment]
It is actually 10x slower on 0.9.2 :(

**Pull request closed without merging**
